// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace prjFriendlyFoodWebAPI.Models;

public partial class FriendlyFoodDbContext : DbContext
{
    public FriendlyFoodDbContext(DbContextOptions<FriendlyFoodDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TApply> TApplies { get; set; }

    public virtual DbSet<TApplyStatus> TApplyStatuses { get; set; }

    public virtual DbSet<TAttachmentTable> TAttachmentTables { get; set; }

    public virtual DbSet<TConversationMember> TConversationMembers { get; set; }

    public virtual DbSet<TConversationMessagesTable> TConversationMessagesTables { get; set; }

    public virtual DbSet<TConversationsTable> TConversationsTables { get; set; }

    public virtual DbSet<TFoodMapFavorite> TFoodMapFavorites { get; set; }

    public virtual DbSet<TFoodMapIngredientCategory> TFoodMapIngredientCategories { get; set; }

    public virtual DbSet<TFoodMapIngredientPlaceCategory> TFoodMapIngredientPlaceCategories { get; set; }

    public virtual DbSet<TFoodMapPlace> TFoodMapPlaces { get; set; }

    public virtual DbSet<TFoodMapPlaceCategory> TFoodMapPlaceCategories { get; set; }

    public virtual DbSet<TFoodMapPlaceImage> TFoodMapPlaceImages { get; set; }

    public virtual DbSet<TFoodMapRecommendationCampaign> TFoodMapRecommendationCampaigns { get; set; }

    public virtual DbSet<TFoodMapRecommendationPlace> TFoodMapRecommendationPlaces { get; set; }

    public virtual DbSet<TFoodMapShoppingList> TFoodMapShoppingLists { get; set; }

    public virtual DbSet<TFoodMapShoppingListItem> TFoodMapShoppingListItems { get; set; }

    public virtual DbSet<TFoodMapTrip> TFoodMapTrips { get; set; }

    public virtual DbSet<TFoodMapTripPlace> TFoodMapTripPlaces { get; set; }

    public virtual DbSet<TFoodMapTripRoute> TFoodMapTripRoutes { get; set; }

    public virtual DbSet<TIngredient> TIngredients { get; set; }

    public virtual DbSet<TMarketCheckoutBatch> TMarketCheckoutBatches { get; set; }

    public virtual DbSet<TMarketCoupon> TMarketCoupons { get; set; }

    public virtual DbSet<TMarketOrder> TMarketOrders { get; set; }

    public virtual DbSet<TMarketOrderDetail> TMarketOrderDetails { get; set; }

    public virtual DbSet<TMarketOrderDiscount> TMarketOrderDiscounts { get; set; }

    public virtual DbSet<TMarketProduct> TMarketProducts { get; set; }

    public virtual DbSet<TMarketProductCategory> TMarketProductCategories { get; set; }

    public virtual DbSet<TMarketProductFavorite> TMarketProductFavorites { get; set; }

    public virtual DbSet<TMarketProductImage> TMarketProductImages { get; set; }

    public virtual DbSet<TMarketProductReview> TMarketProductReviews { get; set; }

    public virtual DbSet<TMarketShoppingCart> TMarketShoppingCarts { get; set; }

    public virtual DbSet<TMessageTable> TMessageTables { get; set; }

    public virtual DbSet<TPostTable> TPostTables { get; set; }

    public virtual DbSet<TRecipe> TRecipes { get; set; }

    public virtual DbSet<TRecipeCategory> TRecipeCategories { get; set; }

    public virtual DbSet<TRecipeFavorite> TRecipeFavorites { get; set; }

    public virtual DbSet<TRecipeIngredient> TRecipeIngredients { get; set; }

    public virtual DbSet<TRecipeLike> TRecipeLikes { get; set; }

    public virtual DbSet<TRecipeStep> TRecipeSteps { get; set; }

    public virtual DbSet<TRecipeTag> TRecipeTags { get; set; }

    public virtual DbSet<TRecipeTagMapping> TRecipeTagMappings { get; set; }

    public virtual DbSet<TRecipeUserPantry> TRecipeUserPantries { get; set; }

    public virtual DbSet<TSeller> TSellers { get; set; }

    public virtual DbSet<TSortTable> TSortTables { get; set; }

    public virtual DbSet<TStatus> TStatuses { get; set; }

    public virtual DbSet<TUser> TUsers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TApply>(entity =>
        {
            entity.HasKey(e => e.FId).HasName("PK__tApply__D9F8227C831518DD");

            entity.ToTable("tApply");

            entity.Property(e => e.FId)
                .ValueGeneratedNever()
                .HasColumnName("fId");
            entity.Property(e => e.FIdCard)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("fIdCard");
            entity.Property(e => e.FIdNum)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("fIdNum");
            entity.Property(e => e.FSendingDate)
                .HasColumnType("datetime")
                .HasColumnName("fSendingDate");
            entity.Property(e => e.FStatus).HasColumnName("fStatus");
            entity.Property(e => e.FStoreDescription)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("fStoreDescription");
            entity.Property(e => e.FStoreName)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("fStoreName");
            entity.Property(e => e.FUserId).HasColumnName("fUserId");

            entity.HasOne(d => d.FStatusNavigation).WithMany(p => p.TApplies)
                .HasForeignKey(d => d.FStatus)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Apply_Status");

            entity.HasOne(d => d.FUser).WithMany(p => p.TApplies)
                .HasForeignKey(d => d.FUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Apply_User");
        });

        modelBuilder.Entity<TApplyStatus>(entity =>
        {
            entity.HasKey(e => e.FId).HasName("PK__tApplySt__D9F8227C0BC14856");

            entity.ToTable("tApplyStatus");

            entity.Property(e => e.FId)
                .ValueGeneratedNever()
                .HasColumnName("fId");
            entity.Property(e => e.FApplyStatusName)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("fApplyStatusName");
        });

        modelBuilder.Entity<TAttachmentTable>(entity =>
        {
            entity.HasKey(e => e.FId);

            entity.ToTable("tAttachmentTable");

            entity.Property(e => e.FId).HasColumnName("fId");
            entity.Property(e => e.FCreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("fCreatedDate");
            entity.Property(e => e.FFileName)
                .IsRequired()
                .HasColumnName("fFileName");
            entity.Property(e => e.FFileSize).HasColumnName("fFileSize");
            entity.Property(e => e.FFileType)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("fFileType");
            entity.Property(e => e.FFileUrl)
                .IsRequired()
                .HasColumnName("fFileUrl");
            entity.Property(e => e.FMessageId).HasColumnName("fMessageId");
            entity.Property(e => e.FMimeType)
                .IsRequired()
                .HasColumnName("fMimeType");

            entity.HasOne(d => d.FMessage).WithMany(p => p.TAttachmentTables)
                .HasForeignKey(d => d.FMessageId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tAttachmentTable_tConversationMessagesTable");
        });

        modelBuilder.Entity<TConversationMember>(entity =>
        {
            entity.HasKey(e => new { e.FConversationId, e.FUserId }).HasName("PK__tConvers__8DB173362E427A37");

            entity.ToTable("tConversationMember");

            entity.Property(e => e.FConversationId).HasColumnName("fConversationId");
            entity.Property(e => e.FUserId).HasColumnName("fUserId");
            entity.Property(e => e.FLastReadDate)
                .HasColumnType("datetime")
                .HasColumnName("fLastReadDate");
            entity.Property(e => e.FLastReadMessageId).HasColumnName("fLastReadMessageId");

            entity.HasOne(d => d.FConversation).WithMany(p => p.TConversationMembers)
                .HasForeignKey(d => d.FConversationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tConversa__fConv__3BFFE745");

            entity.HasOne(d => d.FUser).WithMany(p => p.TConversationMembers)
                .HasForeignKey(d => d.FUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tConversa__fUser__3CF40B7E");
        });

        modelBuilder.Entity<TConversationMessagesTable>(entity =>
        {
            entity.HasKey(e => e.FId);

            entity.ToTable("tConversationMessagesTable");

            entity.Property(e => e.FId).HasColumnName("fId");
            entity.Property(e => e.FContent)
                .IsRequired()
                .HasColumnName("fContent");
            entity.Property(e => e.FConversationId).HasColumnName("fConversationId");
            entity.Property(e => e.FCreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("fCreatedDate");
            entity.Property(e => e.FDeletedDate)
                .HasColumnType("datetime")
                .HasColumnName("fDeletedDate");
            entity.Property(e => e.FMessageType)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("fMessageType");
            entity.Property(e => e.FSenderId).HasColumnName("fSenderId");
            entity.Property(e => e.FUpdatedDate)
                .HasColumnType("datetime")
                .HasColumnName("fUpdatedDate");

            entity.HasOne(d => d.FConversation).WithMany(p => p.TConversationMessagesTables)
                .HasForeignKey(d => d.FConversationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tConversationMessagesTable_tConversationsTable");
        });

        modelBuilder.Entity<TConversationsTable>(entity =>
        {
            entity.HasKey(e => e.FConversationId).HasName("PK_fConversationsTable");

            entity.ToTable("tConversationsTable");

            entity.Property(e => e.FConversationId).HasColumnName("fConversationId");
            entity.Property(e => e.FCreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("fCreatedDate");
            entity.Property(e => e.FUpdatedDate)
                .HasColumnType("datetime")
                .HasColumnName("fUpdatedDate");
        });

        modelBuilder.Entity<TFoodMapFavorite>(entity =>
        {
            entity.HasKey(e => e.FFavoriteId);

            entity.ToTable("tFoodMapFavorite");

            entity.HasIndex(e => new { e.FUserId, e.FPlaceId }, "UQ_tFoodMapFavorite_fMember_fPlace").IsUnique();

            entity.Property(e => e.FFavoriteId).HasColumnName("fFavoriteID");
            entity.Property(e => e.FCreatedTime)
                .HasDefaultValueSql("(sysdatetime())", "DF_tFoodMapFavorite_fCreatedTime")
                .HasColumnName("fCreatedTime");
            entity.Property(e => e.FPlaceId).HasColumnName("fPlaceID");
            entity.Property(e => e.FUserId).HasColumnName("fUserId");

            entity.HasOne(d => d.FPlace).WithMany(p => p.TFoodMapFavorites)
                .HasForeignKey(d => d.FPlaceId)
                .HasConstraintName("FK_tFoodMapFavorite_fPlace");

            entity.HasOne(d => d.FUser).WithMany(p => p.TFoodMapFavorites)
                .HasForeignKey(d => d.FUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FoodMapFavorite_User");
        });

        modelBuilder.Entity<TFoodMapIngredientCategory>(entity =>
        {
            entity.HasKey(e => e.FIngredientCategoryId);

            entity.ToTable("tFoodMapIngredientCategory");

            entity.HasIndex(e => e.FCategoryName, "UQ_tFoodMapIngredientCategory_fCategoryName").IsUnique();

            entity.Property(e => e.FIngredientCategoryId).HasColumnName("fIngredientCategoryID");
            entity.Property(e => e.FCategoryName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("fCategoryName");
            entity.Property(e => e.FCreatedTime)
                .HasDefaultValueSql("(sysdatetime())", "DF_tFoodMapIngredientCategory_CreatedTime")
                .HasColumnName("fCreatedTime");
            entity.Property(e => e.FDescription)
                .HasMaxLength(200)
                .HasColumnName("fDescription");
        });

        modelBuilder.Entity<TFoodMapIngredientPlaceCategory>(entity =>
        {
            entity.HasKey(e => e.FMappingId);

            entity.ToTable("tFoodMapIngredientPlaceCategory");

            entity.HasIndex(e => new { e.FIngredientCategoryId, e.FPlaceCategoryId }, "UQ_tFoodMapIngredientPlaceCategory_fMapping").IsUnique();

            entity.Property(e => e.FMappingId).HasColumnName("fMappingID");
            entity.Property(e => e.FCreatedTime)
                .HasDefaultValueSql("(sysdatetime())", "DF_tFoodMapIngredientPlaceCategory_fCreatedTime")
                .HasColumnName("fCreatedTime");
            entity.Property(e => e.FIngredientCategoryId).HasColumnName("fIngredientCategoryID");
            entity.Property(e => e.FIsActive)
                .HasDefaultValue(true, "DF_tFoodMapIngredientPlaceCategory_fIsActive")
                .HasColumnName("fIsActive");
            entity.Property(e => e.FPlaceCategoryId).HasColumnName("fPlaceCategoryID");
            entity.Property(e => e.FPriority)
                .HasDefaultValue(1, "DF_tFoodMapIngredientPlaceCategory_fPriority")
                .HasColumnName("fPriority");

            entity.HasOne(d => d.FIngredientCategory).WithMany(p => p.TFoodMapIngredientPlaceCategories)
                .HasForeignKey(d => d.FIngredientCategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tFoodMapIngredientPlaceCategory_fIngredientCategory");

            entity.HasOne(d => d.FPlaceCategory).WithMany(p => p.TFoodMapIngredientPlaceCategories)
                .HasForeignKey(d => d.FPlaceCategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tFoodMapIngredientPlaceCategory_fPlaceCategory");
        });

        modelBuilder.Entity<TFoodMapPlace>(entity =>
        {
            entity.HasKey(e => e.FPlaceId);

            entity.ToTable("tFoodMapPlace");

            entity.HasIndex(e => e.FGooglePlaceId, "UQ_tFoodMapPlace_fGooglePlaceID").IsUnique();

            entity.Property(e => e.FPlaceId).HasColumnName("fPlaceID");
            entity.Property(e => e.FAddress)
                .IsRequired()
                .HasMaxLength(300)
                .HasColumnName("fAddress");
            entity.Property(e => e.FBusinessStatus)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("fBusinessStatus");
            entity.Property(e => e.FCreatedTime)
                .HasDefaultValueSql("(sysdatetime())", "DF_tFoodMapPlace_CreatedTime")
                .HasColumnName("fCreatedTime");
            entity.Property(e => e.FDescription).HasColumnName("fDescription");
            entity.Property(e => e.FGooglePlaceId)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("fGooglePlaceID");
            entity.Property(e => e.FGoogleRating)
                .HasColumnType("decimal(2, 1)")
                .HasColumnName("fGoogleRating");
            entity.Property(e => e.FGoogleReviewCount).HasColumnName("fGoogleReviewCount");
            entity.Property(e => e.FIsActive)
                .HasDefaultValue(true, "DF_tFoodMapPlace_fIsActive")
                .HasColumnName("fIsActive");
            entity.Property(e => e.FLatitude)
                .HasColumnType("decimal(10, 7)")
                .HasColumnName("fLatitude");
            entity.Property(e => e.FLongitude)
                .HasColumnType("decimal(10, 7)")
                .HasColumnName("fLongitude");
            entity.Property(e => e.FName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("fName");
            entity.Property(e => e.FPhone)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("fPhone");
            entity.Property(e => e.FPlaceCategoryId).HasColumnName("fPlaceCategoryID");
            entity.Property(e => e.FUpdatedTime).HasColumnName("fUpdatedTime");

            entity.HasOne(d => d.FPlaceCategory).WithMany(p => p.TFoodMapPlaces)
                .HasForeignKey(d => d.FPlaceCategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tFoodMapPlace_fPlaceCategory");
        });

        modelBuilder.Entity<TFoodMapPlaceCategory>(entity =>
        {
            entity.HasKey(e => e.FPlaceCategoryId);

            entity.ToTable("tFoodMapPlaceCategory");

            entity.HasIndex(e => e.FCategoryName, "UQ_tFoodMapPlaceCategory_fCategoryName").IsUnique();

            entity.Property(e => e.FPlaceCategoryId).HasColumnName("fPlaceCategoryID");
            entity.Property(e => e.FCategoryName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("fCategoryName");
            entity.Property(e => e.FCreatedTime)
                .HasDefaultValueSql("(sysdatetime())", "DF_tFoodMapPlaceCategory_fCreatedTime")
                .HasColumnName("fCreatedTime");
            entity.Property(e => e.FDescription)
                .HasMaxLength(200)
                .HasColumnName("fDescription");
        });

        modelBuilder.Entity<TFoodMapPlaceImage>(entity =>
        {
            entity.HasKey(e => e.FImageId);

            entity.ToTable("tFoodMapPlaceImage");

            entity.Property(e => e.FImageId).HasColumnName("fImageID");
            entity.Property(e => e.FCreatedTime)
                .HasDefaultValueSql("(sysdatetime())", "DF_tFoodMapPlaceImage_fCreatedTime")
                .HasColumnName("fCreatedTime");
            entity.Property(e => e.FImageType)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("fImageType");
            entity.Property(e => e.FImageUrl)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("fImageURL");
            entity.Property(e => e.FPlaceId).HasColumnName("fPlaceID");
            entity.Property(e => e.FSortOrder).HasColumnName("fSortOrder");

            entity.HasOne(d => d.FPlace).WithMany(p => p.TFoodMapPlaceImages)
                .HasForeignKey(d => d.FPlaceId)
                .HasConstraintName("FK_tFoodMapPlaceImage_fPlace");
        });

        modelBuilder.Entity<TFoodMapRecommendationCampaign>(entity =>
        {
            entity.HasKey(e => e.FCampaignId);

            entity.ToTable("tFoodMapRecommendationCampaign");

            entity.Property(e => e.FCampaignId).HasColumnName("fCampaignID");
            entity.Property(e => e.FBannerImageUrl)
                .HasMaxLength(500)
                .HasColumnName("fBannerImageURL");
            entity.Property(e => e.FContent).HasColumnName("fContent");
            entity.Property(e => e.FCreatedTime)
                .HasDefaultValueSql("(sysdatetime())", "DF_tFoodMapRecommendationCampaign_fCreatedTime")
                .HasColumnName("fCreatedTime");
            entity.Property(e => e.FEndDate).HasColumnName("fEndDate");
            entity.Property(e => e.FIsActive)
                .HasDefaultValue(true, "DF_tFoodMapRecommendationCampaign_fIsActive")
                .HasColumnName("fIsActive");
            entity.Property(e => e.FPriority).HasColumnName("fPriority");
            entity.Property(e => e.FStartDate).HasColumnName("fStartDate");
            entity.Property(e => e.FTitle)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("fTitle");
            entity.Property(e => e.FUpdatedTime).HasColumnName("fUpdatedTime");
        });

        modelBuilder.Entity<TFoodMapRecommendationPlace>(entity =>
        {
            entity.HasKey(e => e.FCampaignPlaceId);

            entity.ToTable("tFoodMapRecommendationPlace");

            entity.HasIndex(e => new { e.FCampaignId, e.FPlaceId }, "UQ_tFoodMapRecommendationPlace_fCampaign_fPlace").IsUnique();

            entity.Property(e => e.FCampaignPlaceId).HasColumnName("fCampaignPlaceID");
            entity.Property(e => e.FCampaignId).HasColumnName("fCampaignID");
            entity.Property(e => e.FCreatedTime)
                .HasDefaultValueSql("(sysdatetime())", "DF_tFoodMapRecommendationPlace_fCreatedTime")
                .HasColumnName("fCreatedTime");
            entity.Property(e => e.FIsRecommend)
                .HasDefaultValue(true, "DF_tFoodMapRecommendationPlace_fIsRecommend")
                .HasColumnName("fIsRecommend");
            entity.Property(e => e.FPlaceId).HasColumnName("fPlaceID");
            entity.Property(e => e.FSortOrder).HasColumnName("fSortOrder");

            entity.HasOne(d => d.FCampaign).WithMany(p => p.TFoodMapRecommendationPlaces)
                .HasForeignKey(d => d.FCampaignId)
                .HasConstraintName("FK_tFoodMapRecommendationPlace_fCampaign");

            entity.HasOne(d => d.FPlace).WithMany(p => p.TFoodMapRecommendationPlaces)
                .HasForeignKey(d => d.FPlaceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tFoodMapRecommendationPlace_fPlace");
        });

        modelBuilder.Entity<TFoodMapShoppingList>(entity =>
        {
            entity.HasKey(e => e.FShoppingListId);

            entity.ToTable("tFoodMapShoppingList");

            entity.Property(e => e.FShoppingListId).HasColumnName("fShoppingListID");
            entity.Property(e => e.FCreatedTime)
                .HasDefaultValueSql("(sysdatetime())", "DF_tFoodMapShoppingList_fCreatedTime")
                .HasColumnName("fCreatedTime");
            entity.Property(e => e.FListName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("fListName");
            entity.Property(e => e.FStatus)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("Draft", "DF_tFoodMapShoppingList_fStatus")
                .HasColumnName("fStatus");
            entity.Property(e => e.FUpdatedTime).HasColumnName("fUpdatedTime");
            entity.Property(e => e.FUserId).HasColumnName("fUserID");

            entity.HasOne(d => d.FUser).WithMany(p => p.TFoodMapShoppingLists)
                .HasForeignKey(d => d.FUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FoodMapShoppingList_User");
        });

        modelBuilder.Entity<TFoodMapShoppingListItem>(entity =>
        {
            entity.HasKey(e => e.FShoppingItemId);

            entity.ToTable("tFoodMapShoppingListItem");

            entity.Property(e => e.FShoppingItemId).HasColumnName("fShoppingItemID");
            entity.Property(e => e.FCreatedTime)
                .HasDefaultValueSql("(sysdatetime())", "DF_tFoodMapShoppingListItem_fCreatedTime")
                .HasColumnName("fCreatedTime");
            entity.Property(e => e.FIngredientId).HasColumnName("fIngredientID");
            entity.Property(e => e.FIsPurchased).HasColumnName("fIsPurchased");
            entity.Property(e => e.FNote)
                .HasMaxLength(200)
                .HasColumnName("fNote");
            entity.Property(e => e.FQuantity)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("fQuantity");
            entity.Property(e => e.FShoppingListId).HasColumnName("fShoppingListID");
            entity.Property(e => e.FUnit)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("fUnit");
            entity.Property(e => e.FUpdatedTime).HasColumnName("fUpdatedTime");

            entity.HasOne(d => d.FShoppingList).WithMany(p => p.TFoodMapShoppingListItems)
                .HasForeignKey(d => d.FShoppingListId)
                .HasConstraintName("FK_tFoodMapShoppingListItem_fShoppingList");
        });

        modelBuilder.Entity<TFoodMapTrip>(entity =>
        {
            entity.HasKey(e => e.FTripId);

            entity.ToTable("tFoodMapTrip");

            entity.Property(e => e.FTripId).HasColumnName("fTripID");
            entity.Property(e => e.FCreatedTime)
                .HasDefaultValueSql("(sysdatetime())", "DF_tFoodMapTrip_fCreatedTime")
                .HasColumnName("fCreatedTime");
            entity.Property(e => e.FDescription)
                .HasMaxLength(500)
                .HasColumnName("fDescription");
            entity.Property(e => e.FStartTime).HasColumnName("fStartTime");
            entity.Property(e => e.FStatus)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("Draft", "DF_tFoodMapTrip_fStatus")
                .HasColumnName("fStatus");
            entity.Property(e => e.FTripDate).HasColumnName("fTripDate");
            entity.Property(e => e.FTripName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("fTripName");
            entity.Property(e => e.FUpdatedTime).HasColumnName("fUpdatedTime");
            entity.Property(e => e.FUserId).HasColumnName("fUserID");

            entity.HasOne(d => d.FUser).WithMany(p => p.TFoodMapTrips)
                .HasForeignKey(d => d.FUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FoodMapTrip_User");
        });

        modelBuilder.Entity<TFoodMapTripPlace>(entity =>
        {
            entity.HasKey(e => e.FTripPlaceId);

            entity.ToTable("tFoodMapTripPlace");

            entity.HasIndex(e => new { e.FTripId, e.FSortOrder }, "UQ_tFoodMapTripPlace_fTrip_fSortOrder").IsUnique();

            entity.Property(e => e.FTripPlaceId).HasColumnName("fTripPlaceID");
            entity.Property(e => e.FCreatedTime)
                .HasDefaultValueSql("(sysdatetime())", "DF_tFoodMapTripPlace_fCreatedTime")
                .HasColumnName("fCreatedTime");
            entity.Property(e => e.FDistanceFromPrevious)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("fDistanceFromPrevious");
            entity.Property(e => e.FDurationFromPrevious).HasColumnName("fDurationFromPrevious");
            entity.Property(e => e.FNote)
                .HasMaxLength(200)
                .HasColumnName("fNote");
            entity.Property(e => e.FPlaceId).HasColumnName("fPlaceID");
            entity.Property(e => e.FSortOrder).HasColumnName("fSortOrder");
            entity.Property(e => e.FStayMinutes).HasColumnName("fStayMinutes");
            entity.Property(e => e.FTripId).HasColumnName("fTripID");
            entity.Property(e => e.FVisitTime).HasColumnName("fVisitTime");

            entity.HasOne(d => d.FPlace).WithMany(p => p.TFoodMapTripPlaces)
                .HasForeignKey(d => d.FPlaceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tFoodMapTripPlace_fPlace");

            entity.HasOne(d => d.FTrip).WithMany(p => p.TFoodMapTripPlaces)
                .HasForeignKey(d => d.FTripId)
                .HasConstraintName("FK_tFoodMapTripPlace_fTrip");
        });

        modelBuilder.Entity<TFoodMapTripRoute>(entity =>
        {
            entity.HasKey(e => e.FTripRouteId);

            entity.ToTable("tFoodMapTripRoute");

            entity.Property(e => e.FTripRouteId).HasColumnName("fTripRouteID");
            entity.Property(e => e.FCreatedTime)
                .HasDefaultValueSql("(sysdatetime())", "DF_tFoodMapTripRoute_fCreatedTime")
                .HasColumnName("fCreatedTime");
            entity.Property(e => e.FPolyline).HasColumnName("fPolyline");
            entity.Property(e => e.FRouteProvider)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("fRouteProvider");
            entity.Property(e => e.FRouteVersion)
                .HasDefaultValue(1, "DF_tFoodMapTripRoute_fRouteVersion")
                .HasColumnName("fRouteVersion");
            entity.Property(e => e.FTotalDistance)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("fTotalDistance");
            entity.Property(e => e.FTotalDuration).HasColumnName("fTotalDuration");
            entity.Property(e => e.FTripId).HasColumnName("fTripID");
            entity.Property(e => e.FUpdatedTime).HasColumnName("fUpdatedTime");

            entity.HasOne(d => d.FTrip).WithMany(p => p.TFoodMapTripRoutes)
                .HasForeignKey(d => d.FTripId)
                .HasConstraintName("FK_tFoodMapTripRoute_fTrip");
        });

        modelBuilder.Entity<TIngredient>(entity =>
        {
            entity.HasKey(e => e.FId);

            entity.ToTable("tIngredient");

            entity.Property(e => e.FId).HasColumnName("fId");
            entity.Property(e => e.FName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("fName");
        });

        modelBuilder.Entity<TMarketCheckoutBatch>(entity =>
        {
            entity.HasKey(e => e.FBatchId);

            entity.ToTable("tMarketCheckoutBatch", tb => tb.HasComment("結帳批次(對應綠界一次金流交易,底下可包含多張子訂單)"));

            entity.HasIndex(e => e.FBatchNo, "UQ_tMarketCheckoutBatch_fBatchNo").IsUnique();

            entity.HasIndex(e => e.FPaymentTradeNo, "UQ_tMarketCheckoutBatch_fPaymentTradeNo")
                .IsUnique()
                .HasFilter("([fPaymentTradeNo] IS NOT NULL)");

            entity.Property(e => e.FBatchId)
                .HasComment("結帳批次表ID")
                .HasColumnName("fBatchId");
            entity.Property(e => e.FBatchNo)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasComment("商店端唯一,對應綠界MerchantTradeNo")
                .HasColumnName("fBatchNo");
            entity.Property(e => e.FCreatedDate)
                .HasComment("建立日期")
                .HasColumnName("fCreatedDate");
            entity.Property(e => e.FPaidAt)
                .HasComment("實際完成付款成功時間")
                .HasColumnName("fPaidAt");
            entity.Property(e => e.FPaymentMethod)
                .IsRequired()
                .HasMaxLength(50)
                .HasComment("第三方付款方式")
                .HasColumnName("fPaymentMethod");
            entity.Property(e => e.FPaymentStatus)
                .HasComment("付款狀態；0待付款/1已付款/2部分退款/3已退款/4失敗")
                .HasColumnName("fPaymentStatus");
            entity.Property(e => e.FPaymentTradeNo)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasComment("第三方金流交易序號")
                .HasColumnName("fPaymentTradeNo");
            entity.Property(e => e.FTotalAmount)
                .HasComment("批次應付總金額")
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("fTotalAmount");
            entity.Property(e => e.FUserId)
                .HasComment("買家")
                .HasColumnName("fUserId");

            entity.HasOne(d => d.FUser).WithMany(p => p.TMarketCheckoutBatches)
                .HasForeignKey(d => d.FUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tMarketCheckoutBatch_tUser");
        });

        modelBuilder.Entity<TMarketCoupon>(entity =>
        {
            entity.HasKey(e => e.FCouponId);

            entity.ToTable("tMarketCoupon", tb => tb.HasComment("優惠券"));

            entity.HasIndex(e => e.FCode, "UQ_tMarketCoupon_fCode")
                .IsUnique()
                .HasFilter("([fCode] IS NOT NULL)");

            entity.Property(e => e.FCouponId)
                .HasComment("折價卷編號")
                .HasColumnName("fCouponId");
            entity.Property(e => e.FCode)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasComment("優惠碼")
                .HasColumnName("fCode");
            entity.Property(e => e.FDiscountType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasComment("折抵類型")
                .HasColumnName("fDiscountType");
            entity.Property(e => e.FDiscountValue)
                .HasComment("比例折抵值")
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("fDiscountValue");
            entity.Property(e => e.FEndDate)
                .HasComment("活動結束日")
                .HasColumnName("fEndDate");
            entity.Property(e => e.FIsActive)
                .HasComment("優惠卷狀態")
                .HasColumnName("fIsActive");
            entity.Property(e => e.FMaxDiscountAmount)
                .HasComment("打折時的折抵上限（如最多折 $500）")
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("fMaxDiscountAmount");
            entity.Property(e => e.FMinPurchaseAmount)
                .HasComment("最低消費門檻")
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("fMinPurchaseAmount");
            entity.Property(e => e.FName)
                .IsRequired()
                .HasMaxLength(100)
                .HasComment("活動名稱")
                .HasColumnName("fName");
            entity.Property(e => e.FScopeType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasComment("適用範圍")
                .HasColumnName("fScopeType");
            entity.Property(e => e.FSellerId)
                .HasComment("商家編號")
                .HasColumnName("fSellerId");
            entity.Property(e => e.FStartDate)
                .HasComment("活動開始日")
                .HasColumnName("fStartDate");
            entity.Property(e => e.FTotalLimit)
                .HasComment("發行數量限制")
                .HasColumnName("fTotalLimit");
            entity.Property(e => e.FUsedCount)
                .HasComment("已使用數量")
                .HasColumnName("fUsedCount");

            entity.HasOne(d => d.FSeller).WithMany(p => p.TMarketCoupons)
                .HasForeignKey(d => d.FSellerId)
                .HasConstraintName("FK_tMarketCoupon_tSeller");
        });

        modelBuilder.Entity<TMarketOrder>(entity =>
        {
            entity.HasKey(e => e.FOrderId);

            entity.ToTable("tMarketOrder", tb => tb.HasComment("訂單主檔(依賣家分組後的子訂單)"));

            entity.HasIndex(e => e.FOrderNo, "UQ_tMarketOrder_fOrderNo").IsUnique();

            entity.Property(e => e.FOrderId)
                .HasComment("訂單序號")
                .HasColumnName("fOrderID");
            entity.Property(e => e.FBatchId)
                .HasComment("批次ID")
                .HasColumnName("fBatchId");
            entity.Property(e => e.FCancellationStatus)
                .HasComment("取消狀態；0 無取消申請 / 1 待回覆 / 2 已取消 / 3 拒絕取消")
                .HasColumnName("fCancellationStatus");
            entity.Property(e => e.FIsShippingConfirmed)
                .HasComment("賣家是否已確認/列印出貨單；0 未確認 1 已確認/已列印")
                .HasColumnName("fIsShippingConfirmed");
            entity.Property(e => e.FOrderDate)
                .HasComment("訂單日期")
                .HasColumnName("fOrderDate");
            entity.Property(e => e.FOrderNo)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasComment("訂單編號")
                .HasColumnName("fOrderNo");
            entity.Property(e => e.FOrderStatus)
                .HasComment("訂單狀態；0 待處理 / 1 已成立 / 2 已完成 / 3 已取消")
                .HasColumnName("fOrderStatus");
            entity.Property(e => e.FPaymentStatus)
                .HasComment("付款狀態；0 待付款 / 1 已付款 / 2 待退款 / 3 已退款")
                .HasColumnName("fPaymentStatus");
            entity.Property(e => e.FProductDiscount)
                .HasComment("商品折抵金額")
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("fProductDiscount");
            entity.Property(e => e.FRecipientName)
                .IsRequired()
                .HasMaxLength(50)
                .HasComment("收件人姓名")
                .HasColumnName("fRecipientName");
            entity.Property(e => e.FRecipientPhone)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasComment("收件人電話")
                .HasColumnName("fRecipientPhone");
            entity.Property(e => e.FReturnStatus)
                .HasComment("退貨狀態；0 無退貨 / 1 待處理 / 2 已處理")
                .HasColumnName("fReturnStatus");
            entity.Property(e => e.FSellerId)
                .HasComment("商家編號")
                .HasColumnName("fSellerId");
            entity.Property(e => e.FShippingAddress)
                .IsRequired()
                .HasMaxLength(255)
                .HasComment("收件地址")
                .HasColumnName("fShippingAddress");
            entity.Property(e => e.FShippingDiscount)
                .HasComment("運費折抵金額")
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("fShippingDiscount");
            entity.Property(e => e.FShippingFee)
                .HasComment("原始運費")
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("fShippingFee");
            entity.Property(e => e.FShippingMethod)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasComment("配送方式")
                .HasColumnName("fShippingMethod");
            entity.Property(e => e.FShippingStatus)
                .HasComment("運送狀態；0 待出貨 / 1 運送中 / 2 已送達 / 3 運送失敗 / 4 退回包裹運送中 / 5 賣家已取回退件")
                .HasColumnName("fShippingStatus");
            entity.Property(e => e.FTotalAmount)
                .HasComment("應付總金額")
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("fTotalAmount");
            entity.Property(e => e.FUserId)
                .HasComment("會員編號")
                .HasColumnName("fUserId");

            entity.HasOne(d => d.FBatch).WithMany(p => p.TMarketOrders)
                .HasForeignKey(d => d.FBatchId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tMarketOrder_tMarketCheckoutBatch");

            entity.HasOne(d => d.FSeller).WithMany(p => p.TMarketOrders)
                .HasForeignKey(d => d.FSellerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tMarketOrder_tSeller");

            entity.HasOne(d => d.FUser).WithMany(p => p.TMarketOrders)
                .HasForeignKey(d => d.FUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tMarketOrder_tUser");
        });

        modelBuilder.Entity<TMarketOrderDetail>(entity =>
        {
            entity.HasKey(e => e.FOrderDetailsId);

            entity.ToTable("tMarketOrderDetail", tb => tb.HasComment("訂單明細"));

            entity.Property(e => e.FOrderDetailsId)
                .HasComment("訂單明細ID")
                .HasColumnName("fOrderDetailsID");
            entity.Property(e => e.FOrderId)
                .HasComment("訂單ID")
                .HasColumnName("fOrderID");
            entity.Property(e => e.FProductId)
                .HasComment("產品編號")
                .HasColumnName("fProductID");
            entity.Property(e => e.FQuantity)
                .HasComment("產品數量")
                .HasColumnName("fQuantity");
            entity.Property(e => e.FUnitPrice)
                .HasComment("產品單價")
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("fUnitPrice");

            entity.HasOne(d => d.FOrder).WithMany(p => p.TMarketOrderDetails)
                .HasForeignKey(d => d.FOrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tMarketOrderDetail_tMarketOrder");

            entity.HasOne(d => d.FProduct).WithMany(p => p.TMarketOrderDetails)
                .HasForeignKey(d => d.FProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tMarketOrderDetail_tMarketProduct");
        });

        modelBuilder.Entity<TMarketOrderDiscount>(entity =>
        {
            entity.HasKey(e => e.FOrderDiscountId).HasName("PK_tMarketOrderDiscounts");

            entity.ToTable("tMarketOrderDiscount", tb => tb.HasComment("訂單折扣快照(結帳當下優惠券套用紀錄)"));

            entity.Property(e => e.FOrderDiscountId)
                .HasComment("明細 PK")
                .HasColumnName("fOrderDiscountId");
            entity.Property(e => e.FAppliedAmount)
                .HasComment("該次優惠實際折抵金額")
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("fAppliedAmount");
            entity.Property(e => e.FCouponId)
                .HasComment("優惠券 ID")
                .HasColumnName("fCouponId");
            entity.Property(e => e.FDiscountName)
                .IsRequired()
                .HasMaxLength(100)
                .HasComment("活動名稱快照")
                .HasColumnName("fDiscountName");
            entity.Property(e => e.FDiscountScope)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasComment("活動適用範圍快照")
                .HasColumnName("fDiscountScope");
            entity.Property(e => e.FDiscountType)
                .IsRequired()
                .HasMaxLength(20)
                .HasComment("折扣類型快照")
                .HasColumnName("fDiscountType");
            entity.Property(e => e.FOrderId)
                .HasComment("訂單 ID")
                .HasColumnName("fOrderID");

            entity.HasOne(d => d.FCoupon).WithMany(p => p.TMarketOrderDiscounts)
                .HasForeignKey(d => d.FCouponId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tMarketOrderDiscount_tMarketCoupon");

            entity.HasOne(d => d.FOrder).WithMany(p => p.TMarketOrderDiscounts)
                .HasForeignKey(d => d.FOrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tMarketOrderDiscount_tMarketOrder");
        });

        modelBuilder.Entity<TMarketProduct>(entity =>
        {
            entity.HasKey(e => e.FProductId);

            entity.ToTable("tMarketProduct", tb => tb.HasComment("商品主檔"));

            entity.HasIndex(e => e.FProductNo, "UQ_tMarketProduct_fProductNo").IsUnique();

            entity.Property(e => e.FProductId)
                .HasComment("產品序號")
                .HasColumnName("fProductID");
            entity.Property(e => e.FBrandOrOrigin)
                .HasMaxLength(50)
                .HasComment("品牌")
                .HasColumnName("fBrandOrOrigin");
            entity.Property(e => e.FDescription)
                .HasComment("產品描述")
                .HasColumnName("fDescription");
            entity.Property(e => e.FExpirationDate)
                .HasComment("有效期限")
                .HasColumnName("fExpirationDate");
            entity.Property(e => e.FManufacturingDate)
                .HasComment("生產日期")
                .HasColumnName("fManufacturingDate");
            entity.Property(e => e.FPrice)
                .HasComment("單價")
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("fPrice");
            entity.Property(e => e.FProductDate)
                .HasComment("上架日期")
                .HasColumnName("fProductDate");
            entity.Property(e => e.FProductNo)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasComment("產品編號")
                .HasColumnName("fProductNo");
            entity.Property(e => e.FProductStatus)
                .HasDefaultValue((byte)1)
                .HasComment("商品狀態；0 審核中 / 1 架上商品 / 2 已售完 / 3 未上架 / 4 已違規")
                .HasColumnName("fProductStatus");
            entity.Property(e => e.FProductname)
                .IsRequired()
                .HasMaxLength(100)
                .HasComment("產品名稱")
                .HasColumnName("fProductname");
            entity.Property(e => e.FProductsCategoryNo)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("產品類別編號")
                .HasColumnName("fProductsCategoryNo");
            entity.Property(e => e.FReportCount)
                .HasComment("被檢舉次數")
                .HasColumnName("fReportCount");
            entity.Property(e => e.FRowVersion)
                .IsRequired()
                .IsRowVersion()
                .IsConcurrencyToken()
                .HasComment("樂觀並行鎖")
                .HasColumnName("fRowVersion");
            entity.Property(e => e.FSellerId)
                .HasComment("商家編號")
                .HasColumnName("fSellerId");
            entity.Property(e => e.FStock)
                .HasComment("數量")
                .HasColumnName("fStock");

            entity.HasOne(d => d.FProductsCategoryNoNavigation).WithMany(p => p.TMarketProducts)
                .HasPrincipalKey(p => p.FCategoryNo)
                .HasForeignKey(d => d.FProductsCategoryNo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tMarketProduct_tMarketProductCategory");

            entity.HasOne(d => d.FSeller).WithMany(p => p.TMarketProducts)
                .HasForeignKey(d => d.FSellerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tMarketProduct_tSeller");
        });

        modelBuilder.Entity<TMarketProductCategory>(entity =>
        {
            entity.HasKey(e => e.FCategoryId).HasName("PK_tMarketProductsCategory");

            entity.ToTable("tMarketProductCategory", tb => tb.HasComment("商品分類(自我參照,支援多層)"));

            entity.HasIndex(e => e.FCategoryNo, "UQ_tMarketProductCategory_fCategoryNo").IsUnique();

            entity.Property(e => e.FCategoryId)
                .HasComment("產品類別序號")
                .HasColumnName("fCategoryID");
            entity.Property(e => e.FCategoriesName)
                .IsRequired()
                .HasMaxLength(50)
                .HasComment("產品類別名稱")
                .HasColumnName("fCategoriesName");
            entity.Property(e => e.FCategoryNo)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("產品類別編號")
                .HasColumnName("fCategoryNo");
            entity.Property(e => e.FParentCategoryId)
                .HasComment("父類別代號")
                .HasColumnName("fParentCategoryId");

            entity.HasOne(d => d.FParentCategory).WithMany(p => p.InverseFParentCategory)
                .HasForeignKey(d => d.FParentCategoryId)
                .HasConstraintName("FK_tMarketProductCategory_tMarketProductCategory");
        });

        modelBuilder.Entity<TMarketProductFavorite>(entity =>
        {
            entity.HasKey(e => e.FFavoriteId).HasName("PK_tMarketFavorites");

            entity.ToTable("tMarketProductFavorite", tb => tb.HasComment("商品收藏"));

            entity.HasIndex(e => new { e.FUserId, e.FProductId }, "UQ_tMarketProductFavorite_User_Product").IsUnique();

            entity.Property(e => e.FFavoriteId)
                .HasComment("收藏ID")
                .HasColumnName("fFavoriteID");
            entity.Property(e => e.FCreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasComment("加入時間")
                .HasColumnName("fCreatedDate");
            entity.Property(e => e.FProductId)
                .HasComment("產品編號")
                .HasColumnName("fProductID");
            entity.Property(e => e.FUserId)
                .HasComment("會員編號")
                .HasColumnName("fUserId");

            entity.HasOne(d => d.FProduct).WithMany(p => p.TMarketProductFavorites)
                .HasForeignKey(d => d.FProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tMarketProductFavorite_tMarketProduct");

            entity.HasOne(d => d.FUser).WithMany(p => p.TMarketProductFavorites)
                .HasForeignKey(d => d.FUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tMarketProductFavorite_tUser");
        });

        modelBuilder.Entity<TMarketProductImage>(entity =>
        {
            entity.HasKey(e => e.FProductImageId);

            entity.ToTable("tMarketProductImage", tb => tb.HasComment("商品圖片"));

            entity.Property(e => e.FProductImageId)
                .HasComment("圖片ID")
                .HasColumnName("fProductImageID");
            entity.Property(e => e.FCreatedDate)
                .HasComment("建立日期")
                .HasColumnName("fCreatedDate");
            entity.Property(e => e.FImageUrl)
                .IsRequired()
                .HasMaxLength(255)
                .HasComment("圖片網址")
                .HasColumnName("fImageUrl");
            entity.Property(e => e.FProductId)
                .HasComment("產品編號")
                .HasColumnName("fProductID");
            entity.Property(e => e.FSortOrder)
                .HasComment("排序")
                .HasColumnName("fSortOrder");

            entity.HasOne(d => d.FProduct).WithMany(p => p.TMarketProductImages)
                .HasForeignKey(d => d.FProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tMarketProductImage_tMarketProduct");
        });

        modelBuilder.Entity<TMarketProductReview>(entity =>
        {
            entity.HasKey(e => e.FReviewId).HasName("PK_tMarketProductReviews");

            entity.ToTable("tMarketProductReview", tb => tb.HasComment("商品評論"));

            entity.HasIndex(e => e.FOrderDetailsId, "UQ_tMarketProductReview_fOrderDetailsID").IsUnique();

            entity.Property(e => e.FReviewId)
                .HasComment("評論ID")
                .HasColumnName("fReviewID");
            entity.Property(e => e.FComment)
                .HasComment("評論內容")
                .HasColumnName("fComment");
            entity.Property(e => e.FCreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasComment("評論時間")
                .HasColumnName("fCreatedDate");
            entity.Property(e => e.FOrderDetailsId)
                .HasComment("訂單明細ID")
                .HasColumnName("fOrderDetailsID");
            entity.Property(e => e.FProductId)
                .HasComment("產品編號")
                .HasColumnName("fProductID");
            entity.Property(e => e.FRating)
                .HasComment("評分")
                .HasColumnName("fRating");
            entity.Property(e => e.FUserId)
                .HasComment("會員編號")
                .HasColumnName("fUserId");

            entity.HasOne(d => d.FOrderDetails).WithOne(p => p.TMarketProductReview)
                .HasForeignKey<TMarketProductReview>(d => d.FOrderDetailsId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tMarketProductReview_tMarketOrderDetail");

            entity.HasOne(d => d.FProduct).WithMany(p => p.TMarketProductReviews)
                .HasForeignKey(d => d.FProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tMarketProductReview_tMarketProduct");

            entity.HasOne(d => d.FUser).WithMany(p => p.TMarketProductReviews)
                .HasForeignKey(d => d.FUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tMarketProductReview_tUser");
        });

        modelBuilder.Entity<TMarketShoppingCart>(entity =>
        {
            entity.HasKey(e => e.FCartItemId).HasName("PK_tMarketShoppingCarts");

            entity.ToTable("tMarketShoppingCart", tb => tb.HasComment("購物車"));

            entity.Property(e => e.FCartItemId)
                .HasComment("明細唯一識別碼")
                .HasColumnName("fCartItemId");
            entity.Property(e => e.FCreatedDate)
                .HasDefaultValueSql("(sysdatetime())")
                .HasComment("加入時間")
                .HasColumnName("fCreatedDate");
            entity.Property(e => e.FProductId)
                .HasComment("商品 ID")
                .HasColumnName("fProductId");
            entity.Property(e => e.FQuantity)
                .HasComment("購買數量")
                .HasColumnName("fQuantity");
            entity.Property(e => e.FSellerId)
                .HasComment("商家編號")
                .HasColumnName("fSellerId");
            entity.Property(e => e.FUserId)
                .HasComment("會員/買家 ID")
                .HasColumnName("fUserId");

            entity.HasOne(d => d.FProduct).WithMany(p => p.TMarketShoppingCarts)
                .HasForeignKey(d => d.FProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tMarketShoppingCart_tMarketProduct");

            entity.HasOne(d => d.FSeller).WithMany(p => p.TMarketShoppingCarts)
                .HasForeignKey(d => d.FSellerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tMarketShoppingCart_tSeller");

            entity.HasOne(d => d.FUser).WithMany(p => p.TMarketShoppingCarts)
                .HasForeignKey(d => d.FUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tMarketShoppingCart_tUser");
        });

        modelBuilder.Entity<TMessageTable>(entity =>
        {
            entity.HasKey(e => e.FMessageId).HasName("PK_MessageTable");

            entity.ToTable("tMessageTable");

            entity.Property(e => e.FMessageId).HasColumnName("fMessageID");
            entity.Property(e => e.FLikes).HasColumnName("fLikes");
            entity.Property(e => e.FMessageContent)
                .IsRequired()
                .HasColumnName("fMessageContent");
            entity.Property(e => e.FMessageDate)
                .HasColumnType("datetime")
                .HasColumnName("fMessageDate");
            entity.Property(e => e.FMessageState)
                .HasDefaultValue((byte)1, "DF_MessageTable_fMessageState")
                .HasColumnName("fMessageState");
            entity.Property(e => e.FPostId).HasColumnName("fPostID");
            entity.Property(e => e.FReplyMessageId).HasColumnName("fReplyMessageID");
            entity.Property(e => e.FUserId).HasColumnName("fUserId");
            entity.Property(e => e.FViews).HasColumnName("fViews");

            entity.HasOne(d => d.FPost).WithMany(p => p.TMessageTables)
                .HasForeignKey(d => d.FPostId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MessageTable_MessageTable");

            entity.HasOne(d => d.FUser).WithMany(p => p.TMessageTables)
                .HasForeignKey(d => d.FUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Message_User");
        });

        modelBuilder.Entity<TPostTable>(entity =>
        {
            entity.HasKey(e => e.FPostId).HasName("PK_PostTable");

            entity.ToTable("tPostTable");

            entity.Property(e => e.FPostId).HasColumnName("fPostID");
            entity.Property(e => e.FLikes).HasColumnName("fLikes");
            entity.Property(e => e.FPostContent)
                .IsRequired()
                .HasColumnName("fPostContent");
            entity.Property(e => e.FPostDate)
                .HasColumnType("datetime")
                .HasColumnName("fPostDate");
            entity.Property(e => e.FPostState)
                .HasDefaultValue((byte)1, "DF_PostTable_fPostState")
                .HasColumnName("fPostState");
            entity.Property(e => e.FRecipeId).HasColumnName("fRecipeId");
            entity.Property(e => e.FSortId).HasColumnName("fSortId");
            entity.Property(e => e.FTitle)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("fTitle");
            entity.Property(e => e.FUserId).HasColumnName("fUserId");
            entity.Property(e => e.FViews).HasColumnName("fViews");

            entity.HasOne(d => d.FRecipe).WithMany(p => p.TPostTables)
                .HasForeignKey(d => d.FRecipeId)
                .HasConstraintName("FK_tPostTable_tRecipe");

            entity.HasOne(d => d.FSort).WithMany(p => p.TPostTables)
                .HasForeignKey(d => d.FSortId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tPostTable_tSortTable");

            entity.HasOne(d => d.FUser).WithMany(p => p.TPostTables)
                .HasForeignKey(d => d.FUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PostTable_User");
        });

        modelBuilder.Entity<TRecipe>(entity =>
        {
            entity.HasKey(e => e.FRecipeId);

            entity.ToTable("tRecipe");

            entity.Property(e => e.FRecipeId).HasColumnName("fRecipeId");
            entity.Property(e => e.FAiPrepTips).HasColumnName("fAiPrepTips");
            entity.Property(e => e.FCategoryId).HasColumnName("fCategoryId");
            entity.Property(e => e.FCookingMinutes).HasColumnName("fCookingMinutes");
            entity.Property(e => e.FCoverImageUrl)
                .HasMaxLength(500)
                .HasColumnName("fCoverImageUrl");
            entity.Property(e => e.FCreatedAt).HasColumnName("fCreatedAt");
            entity.Property(e => e.FDefaultServings).HasColumnName("fDefaultServings");
            entity.Property(e => e.FDescription)
                .HasMaxLength(500)
                .HasColumnName("fDescription");
            entity.Property(e => e.FFavorites).HasColumnName("fFavorites");
            entity.Property(e => e.FIsAiGenerated).HasColumnName("fIsAiGenerated");
            entity.Property(e => e.FLikes).HasColumnName("fLikes");
            entity.Property(e => e.FStatus).HasColumnName("fStatus");
            entity.Property(e => e.FTitle)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("fTitle");
            entity.Property(e => e.FTotalCalories)
                .HasColumnType("decimal(8, 2)")
                .HasColumnName("fTotalCalories");
            entity.Property(e => e.FUpdatedAt).HasColumnName("fUpdatedAt");
            entity.Property(e => e.FUserId).HasColumnName("fUserId");
            entity.Property(e => e.FViews).HasColumnName("fViews");
            entity.Property(e => e.FYtVideoId)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("fYtVideoId");

            entity.HasOne(d => d.FUser).WithMany(p => p.TRecipes)
                .HasForeignKey(d => d.FUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserId_User");
        });

        modelBuilder.Entity<TRecipeCategory>(entity =>
        {
            entity.HasKey(e => e.FCategoryId);

            entity.ToTable("tRecipeCategory");

            entity.Property(e => e.FCategoryId).HasColumnName("fCategoryId");
            entity.Property(e => e.FCategoryName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("fCategoryName");
            entity.Property(e => e.FDisplayOrder).HasColumnName("fDisplayOrder");
        });

        modelBuilder.Entity<TRecipeFavorite>(entity =>
        {
            entity.HasKey(e => e.FFavoriteId);

            entity.ToTable("tRecipeFavorite");

            entity.Property(e => e.FFavoriteId).HasColumnName("fFavoriteId");
            entity.Property(e => e.FRecipeId).HasColumnName("fRecipeId");
            entity.Property(e => e.FUserId).HasColumnName("fUserId");

            entity.HasOne(d => d.FUser).WithMany(p => p.TRecipeFavorites)
                .HasForeignKey(d => d.FUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RecipeFavorite_User");
        });

        modelBuilder.Entity<TRecipeIngredient>(entity =>
        {
            entity.HasKey(e => e.FRecipeIngredientId);

            entity.ToTable("tRecipeIngredient");

            entity.Property(e => e.FRecipeIngredientId).HasColumnName("fRecipeIngredientId");
            entity.Property(e => e.FBaseAmount)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("fBaseAmount");
            entity.Property(e => e.FDisplayAmount)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("fDisplayAmount");
            entity.Property(e => e.FIngredientId).HasColumnName("fIngredientId");
            entity.Property(e => e.FIsMain).HasColumnName("fIsMain");
            entity.Property(e => e.FRecipeId).HasColumnName("fRecipeId");
            entity.Property(e => e.FSortOrder).HasColumnName("fSortOrder");
            entity.Property(e => e.FStandardUnit)
                .HasMaxLength(20)
                .HasColumnName("fStandardUnit");
        });

        modelBuilder.Entity<TRecipeLike>(entity =>
        {
            entity.HasKey(e => e.FLikeId);

            entity.ToTable("tRecipeLike");

            entity.Property(e => e.FLikeId).HasColumnName("fLikeId");
            entity.Property(e => e.FRecipeId).HasColumnName("fRecipeId");
            entity.Property(e => e.FUserId).HasColumnName("fUserId");

            entity.HasOne(d => d.FUser).WithMany(p => p.TRecipeLikes)
                .HasForeignKey(d => d.FUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RecipeLike_User");
        });

        modelBuilder.Entity<TRecipeStep>(entity =>
        {
            entity.HasKey(e => e.FStepId);

            entity.ToTable("tRecipeStep");

            entity.Property(e => e.FStepId).HasColumnName("fStepId");
            entity.Property(e => e.FImageUrl)
                .HasMaxLength(500)
                .HasColumnName("fImageUrl");
            entity.Property(e => e.FInstruction)
                .IsRequired()
                .HasColumnName("fInstruction");
            entity.Property(e => e.FRecipeId).HasColumnName("fRecipeId");
            entity.Property(e => e.FStepNumber).HasColumnName("fStepNumber");
            entity.Property(e => e.FTimerSeconds).HasColumnName("fTimerSeconds");
        });

        modelBuilder.Entity<TRecipeTag>(entity =>
        {
            entity.HasKey(e => e.FTagId);

            entity.ToTable("tRecipeTag");

            entity.Property(e => e.FTagId).HasColumnName("fTagId");
            entity.Property(e => e.FTagName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("fTagName");
            entity.Property(e => e.FTagType)
                .IsRequired()
                .HasMaxLength(30)
                .HasColumnName("fTagType");
        });

        modelBuilder.Entity<TRecipeTagMapping>(entity =>
        {
            entity.HasKey(e => e.FMappingId);

            entity.ToTable("tRecipeTagMapping");

            entity.Property(e => e.FMappingId).HasColumnName("fMappingId");
            entity.Property(e => e.FRecipeId).HasColumnName("fRecipeId");
            entity.Property(e => e.FTagId).HasColumnName("fTagId");
        });

        modelBuilder.Entity<TRecipeUserPantry>(entity =>
        {
            entity.HasKey(e => e.FPantryId);

            entity.ToTable("tRecipeUserPantry");

            entity.Property(e => e.FPantryId).HasColumnName("fPantryId");
            entity.Property(e => e.FAmount)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("fAmount");
            entity.Property(e => e.FCreatedAt).HasColumnName("fCreatedAt");
            entity.Property(e => e.FExpirationDate).HasColumnName("fExpirationDate");
            entity.Property(e => e.FIngredientId).HasColumnName("fIngredientId");
            entity.Property(e => e.FNote)
                .HasMaxLength(150)
                .HasColumnName("fNote");
            entity.Property(e => e.FStorageLocation)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("冷藏", "DF_Pantry_Storage")
                .HasColumnName("fStorageLocation");
            entity.Property(e => e.FUnit)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("fUnit");
            entity.Property(e => e.FUserId).HasColumnName("fUserId");

            entity.HasOne(d => d.FUser).WithMany(p => p.TRecipeUserPantries)
                .HasForeignKey(d => d.FUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RecipeUserPantry_User");
        });

        modelBuilder.Entity<TSeller>(entity =>
        {
            entity.HasKey(e => e.FId).HasName("PK__tSeller__D9F8227C9C2BF71E");

            entity.ToTable("tSeller");

            entity.Property(e => e.FId).HasColumnName("fId");
            entity.Property(e => e.FApplyDate)
                .HasColumnType("datetime")
                .HasColumnName("fApplyDate");
            entity.Property(e => e.FDescription)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("fDescription");
            entity.Property(e => e.FSellerName)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("fSellerName");
            entity.Property(e => e.FStatus).HasColumnName("fStatus");
            entity.Property(e => e.FUserId).HasColumnName("fUserId");

            entity.HasOne(d => d.FStatusNavigation).WithMany(p => p.TSellers)
                .HasForeignKey(d => d.FStatus)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Seller_Status");

            entity.HasOne(d => d.FUser).WithMany(p => p.TSellers)
                .HasForeignKey(d => d.FUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Seller_User");
        });

        modelBuilder.Entity<TSortTable>(entity =>
        {
            entity.HasKey(e => e.FSortId).HasName("PK_SortTable");

            entity.ToTable("tSortTable");

            entity.Property(e => e.FSortId).HasColumnName("fSortId");
            entity.Property(e => e.FSortName)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("fSortName");
        });

        modelBuilder.Entity<TStatus>(entity =>
        {
            entity.HasKey(e => e.FId).HasName("PK__tStatus__D9F8227C436EF4E5");

            entity.ToTable("tStatus");

            entity.Property(e => e.FId)
                .ValueGeneratedNever()
                .HasColumnName("fId");
            entity.Property(e => e.FStatusName)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("fStatusName");
        });

        modelBuilder.Entity<TUser>(entity =>
        {
            entity.HasKey(e => e.FId).HasName("PK__tUser__D9F8227C4FFDA349");

            entity.ToTable("tUser");

            entity.HasIndex(e => e.FUsername, "UQ__tUser__A8F6564A98DB2DF7").IsUnique();

            entity.Property(e => e.FId).HasColumnName("fId");
            entity.Property(e => e.FAddress)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("fAddress");
            entity.Property(e => e.FCreateTime)
                .HasColumnType("datetime")
                .HasColumnName("fCreateTime");
            entity.Property(e => e.FEmail)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("fEmail");
            entity.Property(e => e.FIdNum)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("fIdNum");
            entity.Property(e => e.FImage)
                .IsUnicode(false)
                .HasColumnName("fImage");
            entity.Property(e => e.FIsActive).HasColumnName("fIsActive");
            entity.Property(e => e.FIsAdmin).HasColumnName("fIsAdmin");
            entity.Property(e => e.FLastLogin)
                .HasColumnType("datetime")
                .HasColumnName("fLastLogin");
            entity.Property(e => e.FPassword)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("fPassword");
            entity.Property(e => e.FPhone)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("fPhone");
            entity.Property(e => e.FUsercode)
                .IsRequired()
                .HasMaxLength(32)
                .IsUnicode(false)
                .HasColumnName("fUsercode");
            entity.Property(e => e.FUsername)
                .IsRequired()
                .HasMaxLength(16)
                .IsUnicode(false)
                .HasColumnName("fUsername");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}