// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

public partial class TAttachmentTable
{
    public int FId { get; set; }

    public int FMessageId { get; set; }

    public string FFileType { get; set; }

    public string FFileName { get; set; }

    public string FFileUrl { get; set; }

    public long FFileSize { get; set; }

    public string FMimeType { get; set; }

    public DateTime FCreatedDate { get; set; }

    public virtual TConversationMessagesTable FMessage { get; set; }
}