// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace prjFriendlyFoodWebAPI.Models;

public partial class TAttachmentTable
{
    public int FId { get; set; }

    public int FMessageId { get; set; }

    public string FFileType { get; set; } = null!;

    public string FFileName { get; set; } = null!;

    public string FFileUrl { get; set; } = null!;

    public long FFileSize { get; set; }

    public string FMimeType { get; set; } = null!;

    public DateTime FCreatedDate { get; set; }

    public virtual TConversationMessagesTable FMessage { get; set; } = null!;
}