// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjFriendlyFoodWebAPI.Models;

public partial class TChatRoom
{
    public int FId { get; set; }

    public int FUser1Id { get; set; }

    public int FUser2Id { get; set; }

    public DateTime FCreatedTime { get; set; }

    public virtual TUser FUser1 { get; set; }

    public virtual TUser FUser2 { get; set; }

    public virtual ICollection<TChat> TChats { get; set; } = new List<TChat>();
}