// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjFriendlyFoodWebAPI.Models;

public partial class TChat
{
    public int FId { get; set; }

    public int FChatRoomId { get; set; }

    public int FSenderId { get; set; }

    public int FMessageType { get; set; }

    public string FContent { get; set; }

    public string FFileName { get; set; }

    public string FFileUrl { get; set; }

    public DateTime FCreatedTime { get; set; }

    public virtual TChatRoom FChatRoom { get; set; }

    public virtual TUser FSender { get; set; }
}