// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjFriendlyFoodWebAPI.Models;

public partial class TConversationMember
{
    public int FConversationId { get; set; }

    public int FUserId { get; set; }

    public int? FLastReadMessageId { get; set; }

    public DateTime? FLastReadDate { get; set; }

    public virtual TConversationsTable FConversation { get; set; }

    public virtual TUser FUser { get; set; }
}