// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjFriendlyFoodWebAPI.Models;

public partial class TConversationMessagesTable
{
    public int FId { get; set; }

    public int FConversationId { get; set; }

    public int FSenderId { get; set; }

    public string FMessageType { get; set; }

    public string FContent { get; set; }

    public DateTime FCreatedDate { get; set; }

    public DateTime FUpdatedDate { get; set; }

    public DateTime? FDeletedDate { get; set; }

    public virtual TConversationsTable FConversation { get; set; }

    public virtual ICollection<TAttachmentTable> TAttachmentTables { get; set; } = new List<TAttachmentTable>();
}