// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjFriendlyFoodWebAPI.Models;

public partial class TExternalLogin
{
    public int FId { get; set; }

    public int FUserId { get; set; }

    public string FProvider { get; set; }

    public string FProviderUserId { get; set; }

    public virtual TUser FUser { get; set; }
}