// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace prjFriendlyFoodWebAPI.Models;

public partial class TFoodMapTripPlace
{
    public int FTripPlaceId { get; set; }

    public int FTripId { get; set; }

    public int FPlaceId { get; set; }

    public int FSortOrder { get; set; }

    public TimeOnly? FVisitTime { get; set; }

    public int? FStayMinutes { get; set; }

    public decimal? FDistanceFromPrevious { get; set; }

    public int? FDurationFromPrevious { get; set; }

    public string? FNote { get; set; }

    public DateTime FCreatedTime { get; set; }

    public virtual TFoodMapPlace FPlace { get; set; } = null!;

    public virtual TFoodMapTrip FTrip { get; set; } = null!;
}