// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjFriendlyFoodWebAPI.Models;

public partial class TFoodMapRecommendationPlace
{
    public int FCampaignPlaceId { get; set; }

    public int FCampaignId { get; set; }

    public int FPlaceId { get; set; }

    public int FSortOrder { get; set; }

    public bool FIsRecommend { get; set; }

    public DateTime FCreatedTime { get; set; }

    public virtual TFoodMapRecommendationCampaign FCampaign { get; set; }

    public virtual TFoodMapPlace FPlace { get; set; }
}