// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

public partial class TFoodMapPlaceImage
{
    public int FImageId { get; set; }

    public int FPlaceId { get; set; }

    public string FImageUrl { get; set; }

    public string FImageType { get; set; }

    public int FSortOrder { get; set; }

    public DateTime FCreatedTime { get; set; }

    public virtual TFoodMapPlace FPlace { get; set; }
}