// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjFriendlyFoodWebAPI.Models;

/// <summary>
/// 優惠券
/// </summary>
public partial class TMarketCoupon
{
    /// <summary>
    /// 折價卷編號
    /// </summary>
    public int FCouponId { get; set; }

    /// <summary>
    /// 商家編號
    /// </summary>
    public int? FSellerId { get; set; }

    /// <summary>
    /// 活動名稱
    /// </summary>
    public string FName { get; set; }

    /// <summary>
    /// 優惠碼
    /// </summary>
    public string FCode { get; set; }

    /// <summary>
    /// 適用範圍 (Shipping: 運費券 / Platform: 全站券 / Store: 賣場券)
    /// </summary>
    public string FScopeType { get; set; }

    /// <summary>
    /// 折抵類型 (Fixed: 固定金額 / Percentage: 比例折扣)
    /// </summary>
    public string FDiscountType { get; set; }

    /// <summary>
    /// 比例折抵值
    /// </summary>
    public decimal FDiscountValue { get; set; }

    /// <summary>
    /// 最低消費門檻
    /// </summary>
    public decimal? FMinPurchaseAmount { get; set; }

    /// <summary>
    /// 打折時的折抵上限（如最多折 $500）
    /// </summary>
    public decimal? FMaxDiscountAmount { get; set; }

    /// <summary>
    /// 發行數量限制
    /// </summary>
    public int? FTotalLimit { get; set; }

    /// <summary>
    /// 已使用數量
    /// </summary>
    public int FUsedCount { get; set; }

    /// <summary>
    /// 活動開始日
    /// </summary>
    public DateTime FStartDate { get; set; }

    /// <summary>
    /// 活動結束日
    /// </summary>
    public DateTime? FEndDate { get; set; }

    /// <summary>
    /// 優惠卷狀態
    /// </summary>
    public bool FIsActive { get; set; }

    public virtual TSeller FSeller { get; set; }

    public virtual ICollection<TMarketOrderDiscount> TMarketOrderDiscounts { get; set; } = new List<TMarketOrderDiscount>();
}