// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjFriendlyFoodWebAPI.Models;

/// <summary>
/// 商品圖片
/// </summary>
public partial class TMarketProductImage
{
    /// <summary>
    /// 圖片ID
    /// </summary>
    public int FProductImageId { get; set; }

    /// <summary>
    /// 產品編號
    /// </summary>
    public int FProductId { get; set; }

    /// <summary>
    /// 圖片網址
    /// </summary>
    public string FImageUrl { get; set; }

    /// <summary>
    /// 排序
    /// </summary>
    public short FSortOrder { get; set; }

    /// <summary>
    /// 建立日期
    /// </summary>
    public DateTime FCreatedDate { get; set; }

    public virtual TMarketProduct FProduct { get; set; }
}