// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjFriendlyFoodWebAPI.Models;

/// <summary>
/// 商品分類(自我參照,支援多層)
/// </summary>
public partial class TMarketProductCategory
{
    /// <summary>
    /// 產品類別序號
    /// </summary>
    public long FCategoryId { get; set; }

    /// <summary>
    /// 產品類別編號
    /// </summary>
    public string FCategoryNo { get; set; }

    /// <summary>
    /// 產品類別名稱
    /// </summary>
    public string FCategoriesName { get; set; }

    /// <summary>
    /// 父類別代號
    /// </summary>
    public long? FParentCategoryId { get; set; }

    public virtual TMarketProductCategory FParentCategory { get; set; }

    public virtual ICollection<TMarketProductCategory> InverseFParentCategory { get; set; } = new List<TMarketProductCategory>();

    public virtual ICollection<TMarketProduct> TMarketProducts { get; set; } = new List<TMarketProduct>();
}