// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

/// <summary>
/// 商品評論
/// </summary>
public partial class TMarketProductReview
{
    /// <summary>
    /// 評論ID
    /// </summary>
    public int FReviewId { get; set; }

    /// <summary>
    /// 訂單明細ID
    /// </summary>
    public int FOrderDetailsId { get; set; }

    /// <summary>
    /// 產品編號
    /// </summary>
    public int FProductId { get; set; }

    /// <summary>
    /// 會員編號
    /// </summary>
    public int FUserId { get; set; }

    /// <summary>
    /// 評分
    /// </summary>
    public byte FRating { get; set; }

    /// <summary>
    /// 評論內容
    /// </summary>
    public string FComment { get; set; }

    /// <summary>
    /// 評論時間
    /// </summary>
    public DateTime FCreatedDate { get; set; }

    public virtual TMarketOrderDetail FOrderDetails { get; set; }

    public virtual TMarketProduct FProduct { get; set; }

    public virtual TUser FUser { get; set; }
}