// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjFriendlyFoodWebAPI.Models;

public partial class TMessageTable
{
    public int FMessageId { get; set; }

    public int FPostId { get; set; }

    public int FUserId { get; set; }

    public int? FReplyMessageId { get; set; }

    public string FMessageContent { get; set; }

    public int FLikes { get; set; }

    public DateTime FMessageDate { get; set; }

    public byte FMessageState { get; set; }

    public virtual TPostTable FPost { get; set; }

    public virtual TUser FUser { get; set; }

    public virtual TUser FUser { get; set; } = null!;

    public virtual ICollection<TUser> FUsers { get; set; } = new List<TUser>();
    public virtual ICollection<TMessageLike> TMessageLikes { get; set; } = new List<TMessageLike>();
}