// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjFriendlyFoodWebAPI.Models;

public partial class TMessageLike
{
    public int FMessageLikeId { get; set; }

    public int FMessageId { get; set; }

    public int FUserId { get; set; }

    public virtual TMessageTable FMessage { get; set; }

    public virtual TUser FUser { get; set; }
}