// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

public partial class TPostLike
{
    public int FPostId { get; set; }

    public int FUserId { get; set; }

    public virtual TPostTable FPost { get; set; }
}