// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjFriendlyFoodWebAPI.Models;

public partial class TRecipeTag
{
    public int FTagId { get; set; }

    public string FTagType { get; set; }

    public string FTagName { get; set; }
}