// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

public partial class TRecipeLike
{
    public int FLikeId { get; set; }

    public int FUserId { get; set; }

    public int FRecipeId { get; set; }

    public virtual TUser FUser { get; set; }
}