// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

public partial class TRecipeStep
{
    public int FStepId { get; set; }

    public int FRecipeId { get; set; }

    public short FStepNumber { get; set; }

    public string FInstruction { get; set; }

    public string FImageUrl { get; set; }

    public int FTimerSeconds { get; set; }
}