// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjFriendlyFoodWebAPI.Models;

public partial class TRecipe
{
    public int FRecipeId { get; set; }

    public int FUserId { get; set; }

    public int FCategoryId { get; set; }

    public string FTitle { get; set; }

    public string FDescription { get; set; }

    public string FCoverImageUrl { get; set; }

    public string FYtVideoId { get; set; }

    public string FAiPrepTips { get; set; }

    public bool FIsAiGenerated { get; set; }

    public int FDefaultServings { get; set; }

    public int FCookingMinutes { get; set; }

    public decimal FTotalCalories { get; set; }

    public int FViews { get; set; }

    public int FLikes { get; set; }

    public int FFavorites { get; set; }

    public byte FStatus { get; set; }

    public DateTime FCreatedAt { get; set; }

    public DateTime FUpdatedAt { get; set; }

    public virtual TUser FUser { get; set; }

    public virtual ICollection<TPostTable> TPostTables { get; set; } = new List<TPostTable>();
}