// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace prjFriendlyFoodWebAPI.Models;

public partial class TRecipeFavorite
{
    public int FFavoriteId { get; set; }

    public int FUserId { get; set; }

    public int FRecipeId { get; set; }

    public virtual TUser FUser { get; set; } = null!;
}