// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjFriendlyFoodWebAPI.Models;

public partial class TSortTable
{
    public int FSortId { get; set; }

    public string FSortName { get; set; }

    public virtual ICollection<TPostTable> TPostTables { get; set; } = new List<TPostTable>();
}