// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

public partial class TFoodMapPlaceCategory
{
    public int FPlaceCategoryId { get; set; }

    public string FCategoryName { get; set; }

    public string FDescription { get; set; }

    public DateTime FCreatedTime { get; set; }

    public virtual ICollection<TFoodMapIngredientPlaceCategory> TFoodMapIngredientPlaceCategories { get; set; } = new List<TFoodMapIngredientPlaceCategory>();

    public virtual ICollection<TFoodMapPlace> TFoodMapPlaces { get; set; } = new List<TFoodMapPlace>();
}