// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

public partial class TFoodMapShoppingList
{
    public int FShoppingListId { get; set; }

    public int FUserId { get; set; }

    public string FListName { get; set; }

    public string FStatus { get; set; }

    public DateTime FCreatedTime { get; set; }

    public DateTime? FUpdatedTime { get; set; }

    public virtual TUser FUser { get; set; }

    public virtual ICollection<TFoodMapShoppingListItem> TFoodMapShoppingListItems { get; set; } = new List<TFoodMapShoppingListItem>();
}