// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

public partial class TMessageTable
{
    public int FMessageId { get; set; }

    public int FPostId { get; set; }

    public int FUserId { get; set; }

    public int FReplyMessageId { get; set; }

    public string FMessageContent { get; set; }

    public int FLikes { get; set; }

    public int FViews { get; set; }

    public DateTime FMessageDate { get; set; }

    public byte FMessageState { get; set; }

    public virtual TPostTable FPost { get; set; }

    public virtual TUser FUser { get; set; }
}