// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

public partial class TPostTable
{
    public int FPostId { get; set; }

    public int FUserId { get; set; }

    public string FTitle { get; set; }

    public string FPostContent { get; set; }

    public int FLikes { get; set; }

    public int FViews { get; set; }

    public DateTime FPostDate { get; set; }

    public byte FPostState { get; set; }

    public int FSortId { get; set; }

    public int? FRecipeId { get; set; }

    public virtual TRecipe FRecipe { get; set; }

    public virtual TSortTable FSort { get; set; }

    public virtual TUser FUser { get; set; }

    public virtual ICollection<TMessageTable> TMessageTables { get; set; } = new List<TMessageTable>();
}