// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

public partial class TRecipeTagMapping
{
    public int FMappingId { get; set; }

    public int FRecipeId { get; set; }

    public int FTagId { get; set; }
}