// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

public partial class TRecipeCategory
{
    public int FCategoryId { get; set; }

    public string FCategoryName { get; set; }

    public short FDisplayOrder { get; set; }
}