// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

public partial class TUser
{
    public int FId { get; set; }

    public string FUsername { get; set; }

    public string FPassword { get; set; }

    public string FEmail { get; set; }

    public string FPhone { get; set; }

    public string FIdNum { get; set; }

    public string FAddress { get; set; }

    public string FImage { get; set; }

    public bool FIsActive { get; set; }

    public bool FIsAdmin { get; set; }

    public DateTime FCreateTime { get; set; }

    public DateTime? FLastLogin { get; set; }

    public virtual ICollection<TApply> TApplies { get; set; } = new List<TApply>();

    public virtual ICollection<TConversationMember> TConversationMembers { get; set; } = new List<TConversationMember>();

    public virtual ICollection<TFoodMapFavorite> TFoodMapFavorites { get; set; } = new List<TFoodMapFavorite>();

    public virtual ICollection<TFoodMapShoppingList> TFoodMapShoppingLists { get; set; } = new List<TFoodMapShoppingList>();

    public virtual ICollection<TFoodMapTrip> TFoodMapTrips { get; set; } = new List<TFoodMapTrip>();

    public virtual ICollection<TMarketCheckoutBatch> TMarketCheckoutBatches { get; set; } = new List<TMarketCheckoutBatch>();

    public virtual ICollection<TMarketOrder> TMarketOrders { get; set; } = new List<TMarketOrder>();

    public virtual ICollection<TMarketProductFavorite> TMarketProductFavorites { get; set; } = new List<TMarketProductFavorite>();

    public virtual ICollection<TMarketProductReview> TMarketProductReviews { get; set; } = new List<TMarketProductReview>();

    public virtual ICollection<TMarketShoppingCart> TMarketShoppingCarts { get; set; } = new List<TMarketShoppingCart>();

    public virtual ICollection<TMessageTable> TMessageTables { get; set; } = new List<TMessageTable>();

    public virtual ICollection<TPostTable> TPostTables { get; set; } = new List<TPostTable>();

    public virtual ICollection<TRecipeFavorite> TRecipeFavorites { get; set; } = new List<TRecipeFavorite>();

    public virtual ICollection<TRecipeLike> TRecipeLikes { get; set; } = new List<TRecipeLike>();

    public virtual ICollection<TRecipeUserPantry> TRecipeUserPantries { get; set; } = new List<TRecipeUserPantry>();

    public virtual ICollection<TRecipe> TRecipes { get; set; } = new List<TRecipe>();

    public virtual ICollection<TSeller> TSellers { get; set; } = new List<TSeller>();
}